<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Bookstore.Data</AssemblyName>
    <RootNamespace>Bookstore.Data</RootNamespace>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Bookstore.Domain\Bookstore.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="AWSSDK.Core" Version="4.0.0.29" />
    <PackageReference Include="AWSSDK.Rekognition" Version="4.0.1.11" />
    <PackageReference Include="AWSSDK.S3" Version="4.0.7.7" />
    <PackageReference Include="EntityFramework" Version="6.5.1" />
    <PackageReference Include="Magick.NET.Core" Version="14.8.2" />
    <PackageReference Include="Magick.NET-Q8-AnyCPU" Version="14.8.2" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="*" />
  </ItemGroup>
</Project>