<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Bookstore.Domain</AssemblyName>
    <RootNamespace>Bookstore.Domain</RootNamespace>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="EntityFramework" Version="6.5.1" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="*" />
    <PackageReference Include="Microsoft.AspNetCore.SystemWebAdapters" Version="2.0.0" />
  </ItemGroup>
</Project>